CREATE TABLE IF NOT EXISTS full_dataset (
    track_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    artist TEXT CONSTRAINT art_constr CHECK ((char_length(artist) >=1) AND (char_length(artist) < 255)) NOT NULL,
    track TEXT CONSTRAINT text_constr CHECK ((char_length(track) >= 1) AND (char_length(track) < 255)) NOT NULL,
    album TEXT CONSTRAINT album_constr CHECK ((char_length(album) >=1) AND (char_length(album) < 255)) NOT NULL,
    album_type TEXT CONSTRAINT al_type_constr CHECK (album_type IN ('single', 'compilation', 'album')) NOT NULL,
    danceability float4 NOT NULL,
    energy float4 NOT NULL,
    loudness float4 NOT NULL,
    speechiness float4 NOT NULL,
    acousticness float4 NOT NULL,
    instrumentalness float4 NOT NULL,
    liveness float4 NOT NULL,
    valence float4 NOT NULL,
    tempo float4 NOT NULL,
    duration_min float4 NOT NULL,
    title_youtube TEXT CHECK (char_length(title_youtube) >= 1) NOT NULL,
    channel TEXT CONSTRAINT ch_constr CHECK ((char_length(channel) >=1) AND (char_length(channel) < 255)) NOT NULL,
    views_youtube bigint NOT NULL,
    likes_youtube bigint NOT NULL,
    comments_youtube bigint NOT NULL,
    licensed BOOL NOT NULL,
    official_video BOOL NOT NULL,
    streams_spotify bigint NOT NULL,
    energyliveness float4 NOT NULL,
    most_playedon TEXT CONSTRAINT played_on_constr CHECK (most_playedon IN ('Youtube','Spotify')) NOT NULL
);